# Testing development setup in https://warehouse.readthedocs.io/development/getting-started.html

name: Dev Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make build
      - run: |
          # `make serve` daemonized
          docker-compose up -d
      - run: docker-compose ps
      - run: ./bin/wait-for-db.sh
      - run: make initdb
      - run: make tests
